services:

  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
      - "127.0.0.1:9507:3306"

  nginx:
    image: nginx:alpine
    container_name: tg-parser-nginx
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./web-api:/app
      - ./web-api/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-api

  web-api:
    build: ./web-api
    container_name: tg-parser-web-api
    restart: unless-stopped
    volumes:
      - ./web-api:/app
      - ./media:/app/media
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=parser
      - DB_USER=root
      - DB_PASSWORD=
    depends_on:
      - mysql

networks:
  default:
    name: tg-parser
